Add rating
aDukeFan/java-explore-with-me pull request #3
Opened 2024-08-19 17:42 UTC by aDukeFan

2024-08-22 17:50 UTC, afomkina commented
Привет! Я не могу проверять работу, пока не проходят тесты на github. Нужно обратиться к наставнику за помощью

2024-08-22 19:49 UTC, aDukeFan commented
Привет! Написал тесты учитывающие предыдущую проверку main service, предыдущие оставил в папке Postman под другим названием, чтобы не было конфликтов на GitHub (жалко было удалять 79 штук =)

2024-08-23 12:20 UTC, afomkina requested changes

2024-08-23 12:20 UTC, afomkina commented on main-service/src/main/java/ru/practicum/ewm/main/controller/UserController.java
> +    // to pass Postman tests on GitHub
Лучше удалить данный комментарий

2024-08-23 12:20 UTC, afomkina commented on README.md
Добавь, пожалуйста, в README описание проекта и основные эндпоинты. Также будет полезно указать, как правильно запускать приложение.

2024-08-24 11:59 UTC, afomkina approved these changes

2024-08-24 12:11 UTC, merged